environment:
  COVERALLS_REPO_TOKEN:
    secure: 01/8Z8oeHBp0GEYJhobtRFiPM/ZUSmkRLgu+BmxV8kgNP752XYu78DTqZB7xct3w
configuration: Release
platform: Any CPU
install:
  - choco install gitversion.portable -y
before_build:
  - cmd: nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo ..\AssemblyInfoCommon.cs  /b (get-item env:APPVEYOR_REPO_BRANCH).Value
build:
  project: AdiePlayground.sln
  verbosity: minimal
after_test:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-filter:+[*]* -[Mehdime.Entity]* -[*Tests]*" -target:packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe -targetargs:test\unit\unit-tests.nunit -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*Designer.cs -output:coverage.xml
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
