//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdiePlayground.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdiePlayground.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided apple colour was invalid..
        /// </summary>
        internal static string AppleAppleColorInvalid {
            get {
                return ResourceManager.GetString("AppleAppleColorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided ITimeProvider was invalid..
        /// </summary>
        internal static string ConsoleInstrumentationReporterDateTimeProviderNull {
            get {
                return ResourceManager.GetString("ConsoleInstrumentationReporterDateTimeProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided GuidProvider was invalid..
        /// </summary>
        internal static string ConsoleInstrumentationReporterGuidProviderNull {
            get {
                return ResourceManager.GetString("ConsoleInstrumentationReporterGuidProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided MethodInvocationCounter was invalid..
        /// </summary>
        internal static string ConsoleInstrumentationReporterMethodInvocationCounterNull {
            get {
                return ResourceManager.GetString("ConsoleInstrumentationReporterMethodInvocationCounterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided MethodInvocationTimer was invalid..
        /// </summary>
        internal static string ConsoleInstrumentationReporterMethodInvocationTimerNull {
            get {
                return ResourceManager.GetString("ConsoleInstrumentationReporterMethodInvocationTimerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided ITimeProvider was invalid..
        /// </summary>
        internal static string ConsoleRegistrarDateTimeProviderNull {
            get {
                return ResourceManager.GetString("ConsoleRegistrarDateTimeProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value was invalid..
        /// </summary>
        internal static string FruitContravariantGetValueInputNull {
            get {
                return ResourceManager.GetString("FruitContravariantGetValueInputNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided quality was invalid. Must be between {0} and {1}..
        /// </summary>
        internal static string FruitInvalidQuality {
            get {
                return ResourceManager.GetString("FruitInvalidQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IGuidProvider was invalid..
        /// </summary>
        internal static string InstrumentationInterceptorGuidProviderNull {
            get {
                return ResourceManager.GetString("InstrumentationInterceptorGuidProviderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided MethodInvocationCounter was invalid..
        /// </summary>
        internal static string InstrumentationInterceptorMethodInvocationCounterNull {
            get {
                return ResourceManager.GetString("InstrumentationInterceptorMethodInvocationCounterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided MethodInvocationTimer was invalid..
        /// </summary>
        internal static string InstrumentationInterceptorMethodInvocationTimerNull {
            get {
                return ResourceManager.GetString("InstrumentationInterceptorMethodInvocationTimerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IRegistrar collection was invalid..
        /// </summary>
        internal static string InstrumentationInterceptorRegistrarsNull {
            get {
                return ResourceManager.GetString("InstrumentationInterceptorRegistrarsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided was not a valid ISO 3166-1 alpha-2 country code..
        /// </summary>
        internal static string Iso3166CountryCodeInvalid {
            get {
                return ResourceManager.GetString("Iso3166CountryCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value was invalid..
        /// </summary>
        internal static string OrangeInvariantGetValueInputNull {
            get {
                return ResourceManager.GetString("OrangeInvariantGetValueInputNull", resourceCulture);
            }
        }
    }
}
