//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdiePlayground.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdiePlayground.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;Enter&gt; to continue....
        /// </summary>
        internal static string ConsolePressEnterToContinue {
            get {
                return ResourceManager.GetString("ConsolePressEnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string ContravarianceExampleAppleValue {
            get {
                return ResourceManager.GetString("ContravarianceExampleAppleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string ContravarianceExampleOrangeValue {
            get {
                return ResourceManager.GetString("ContravarianceExampleOrangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running contravariance example..
        /// </summary>
        internal static string ContravarianceExampleRunning {
            get {
                return ResourceManager.GetString("ContravarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is {1}..
        /// </summary>
        internal static string CovarianceExampleFruitColor {
            get {
                return ResourceManager.GetString("CovarianceExampleFruitColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.ToString() = {1}..
        /// </summary>
        internal static string CovarianceExampleObjString {
            get {
                return ResourceManager.GetString("CovarianceExampleObjString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running covariance example..
        /// </summary>
        internal static string CovarianceExampleRunning {
            get {
                return ResourceManager.GetString("CovarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running interception example..
        /// </summary>
        internal static string InterceptionExampleRunning {
            get {
                return ResourceManager.GetString("InterceptionExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string InvarianceExampleFruitValue {
            get {
                return ResourceManager.GetString("InvarianceExampleFruitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string InvarianceExampleOrangeValue {
            get {
                return ResourceManager.GetString("InvarianceExampleOrangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running invariance example..
        /// </summary>
        internal static string InvarianceExampleRunning {
            get {
                return ResourceManager.GetString("InvarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roommate wanted..
        /// </summary>
        internal static string ObserverExampleMessage1 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desk for sale. £35 o.n.o..
        /// </summary>
        internal static string ObserverExampleMessage2 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bassist wanted for classical psychedelic electronic punk rock band!.
        /// </summary>
        internal static string ObserverExampleMessage3 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running observer example..
        /// </summary>
        internal static string ObserverExampleRunning {
            get {
                return ResourceManager.GetString("ObserverExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying bubble sort to a copy of the list:.
        /// </summary>
        internal static string StrategyExampleApplyingBubbleSort {
            get {
                return ResourceManager.GetString("StrategyExampleApplyingBubbleSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying quicksort to a copy of the list:.
        /// </summary>
        internal static string StrategyExampleApplyingQuicksort {
            get {
                return ResourceManager.GetString("StrategyExampleApplyingQuicksort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original list:.
        /// </summary>
        internal static string StrategyExampleOriginalList {
            get {
                return ResourceManager.GetString("StrategyExampleOriginalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running strategy example..
        /// </summary>
        internal static string StrategyExampleRunning {
            get {
                return ResourceManager.GetString("StrategyExampleRunning", resourceCulture);
            }
        }
    }
}
