//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdiePlayground.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdiePlayground.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing redo:.
        /// </summary>
        internal static string CommandExampleRedo {
            get {
                return ResourceManager.GetString("CommandExampleRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning robot drill on:.
        /// </summary>
        internal static string CommandExampleRobotDrillOn {
            get {
                return ResourceManager.GetString("CommandExampleRobotDrillOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving robot {0:0.00} metres:.
        /// </summary>
        internal static string CommandExampleRobotMove {
            get {
                return ResourceManager.GetString("CommandExampleRobotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning robot {0:0.00} radians:.
        /// </summary>
        internal static string CommandExampleRobotTurn {
            get {
                return ResourceManager.GetString("CommandExampleRobotTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running command example..
        /// </summary>
        internal static string CommandExampleRunning {
            get {
                return ResourceManager.GetString("CommandExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing undo:.
        /// </summary>
        internal static string CommandExampleUndo {
            get {
                return ResourceManager.GetString("CommandExampleUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string CommandHelpText {
            get {
                return ResourceManager.GetString("CommandHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command &apos;{0}&apos;..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments on command &apos;{0}&apos;..
        /// </summary>
        internal static string CommandResolveFailed {
            get {
                return ResourceManager.GetString("CommandResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: {0} {1}.
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string ContravarianceExampleAppleValue {
            get {
                return ResourceManager.GetString("ContravarianceExampleAppleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string ContravarianceExampleOrangeValue {
            get {
                return ResourceManager.GetString("ContravarianceExampleOrangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running contravariance example..
        /// </summary>
        internal static string ContravarianceExampleRunning {
            get {
                return ResourceManager.GetString("ContravarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is {1}..
        /// </summary>
        internal static string CovarianceExampleFruitColor {
            get {
                return ResourceManager.GetString("CovarianceExampleFruitColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.ToString() = {1}..
        /// </summary>
        internal static string CovarianceExampleObjString {
            get {
                return ResourceManager.GetString("CovarianceExampleObjString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running covariance example..
        /// </summary>
        internal static string CovarianceExampleRunning {
            get {
                return ResourceManager.GetString("CovarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the example to run..
        /// </summary>
        internal static string ExampleCommandExampleNameHelp {
            get {
                return ResourceManager.GetString("ExampleCommandExampleNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the example with the specified name..
        /// </summary>
        internal static string ExampleCommandHelp {
            get {
                return ResourceManager.GetString("ExampleCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the names of all the examples which can be run..
        /// </summary>
        internal static string ExampleListCommandHelp {
            get {
                return ResourceManager.GetString("ExampleListCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find example named &apos;{0}&apos;..
        /// </summary>
        internal static string ExampleNotFound {
            get {
                return ResourceManager.GetString("ExampleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the program..
        /// </summary>
        internal static string ExitCommandHelp {
            get {
                return ResourceManager.GetString("ExitCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command to display help for; leave empty to show all commands..
        /// </summary>
        internal static string HelpCommandCommandNameHelp {
            get {
                return ResourceManager.GetString("HelpCommandCommandNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays help for commands..
        /// </summary>
        internal static string HelpCommandHelp {
            get {
                return ResourceManager.GetString("HelpCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running interception example..
        /// </summary>
        internal static string InterceptionExampleRunning {
            get {
                return ResourceManager.GetString("InterceptionExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string InvarianceExampleFruitValue {
            get {
                return ResourceManager.GetString("InvarianceExampleFruitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}..
        /// </summary>
        internal static string InvarianceExampleOrangeValue {
            get {
                return ResourceManager.GetString("InvarianceExampleOrangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running invariance example..
        /// </summary>
        internal static string InvarianceExampleRunning {
            get {
                return ResourceManager.GetString("InvarianceExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roommate wanted..
        /// </summary>
        internal static string ObserverExampleMessage1 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desk for sale. £35 o.n.o..
        /// </summary>
        internal static string ObserverExampleMessage2 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bassist wanted for classical psychedelic electronic punk rock band!.
        /// </summary>
        internal static string ObserverExampleMessage3 {
            get {
                return ResourceManager.GetString("ObserverExampleMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running observer example..
        /// </summary>
        internal static string ObserverExampleRunning {
            get {
                return ResourceManager.GetString("ObserverExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying bubble sort to a copy of the list:.
        /// </summary>
        internal static string StrategyExampleApplyingBubbleSort {
            get {
                return ResourceManager.GetString("StrategyExampleApplyingBubbleSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying quicksort to a copy of the list:.
        /// </summary>
        internal static string StrategyExampleApplyingQuicksort {
            get {
                return ResourceManager.GetString("StrategyExampleApplyingQuicksort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original list:.
        /// </summary>
        internal static string StrategyExampleOriginalList {
            get {
                return ResourceManager.GetString("StrategyExampleOriginalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running strategy example..
        /// </summary>
        internal static string StrategyExampleRunning {
            get {
                return ResourceManager.GetString("StrategyExampleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AdiePlayground. Type &apos;help&apos; to get started..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
